apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: frontend
  namespace: argocd

spec:

  project: world-info-project

  source:
    repoURL: https://github.com/YOUR_USERNAME/world-info-app.git
    targetRevision: main
    path: helm/frontend

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true