replicaCount: 2

image:
  repository: YOUR_ECR_REPO/backend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: alb

resources:
  requests:
    cpu: 200m
    memory: 256Mi

  limits:
    cpu: 1
    memory: 1Gi

autoscaling:
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70